import os
path = '/teamspace/studios/thesisdata/Modified_BigSmall/data/MDMER/PreprocessedData/TRAINING_MDMER_SizeW128_SizeH128_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_CropFaceFalse_BackendHC_LargeBoxFalse_LargeSize1.5_DynamicDetFalse_DetLength30_MedianFaceBoxFalse/TRAINING_MDMER_SizeW128_SizeH128_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_CropFaceFalse_BackendHC_LargeBoxFalse_LargeSize1.5_DynamicDetFalse_DetLength30_MedianFaceBoxFalse/'
data = os.listdir(path)

print(data)