BASE: [''] # ALL ARE NOT FINAL
TOOLBOX_MODE: "train_and_test"  # "train_and_test", "only_test", "only_preprocess"

TRAIN:
  BATCH_SIZE: 4 # Original BigSmall: 180
  EPOCHS: 70 # Original BigSmall: 5
  LR: 9e-3 # Original BigSmall: 1e-3 
  MODEL_FILE_NAME: UBFCrPPG_BigSmall
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30 # FPS of the video data
    DATASET: UBFCrPPG_BigSmall
    DO_PREPROCESS: True # If first time, should be True 
    DATA_FORMAT: NDCHW # NCDHW
    DATA_PATH: "data/UBFC-rPPG/RawData" # Raw dataset path, need to be updated
    CACHED_PATH: "data/UBFC-rPPG/PreprocessedData" # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "" 
    BEGIN: 0.0 
    END: 0.7
    PREPROCESS:
      USE_PSUEDO_PPG_LABEL: True
      DATA_TYPE: ['DiffNormalized','Standardized'] # Can have multiple data type: ['Raw', 'DiffNormalized', 'Standardized']
      DATA_AUG: ['None'] # 'None' or 'Motion'. Use motion if the data is an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized # Can only choose ONE label type: ['Raw', 'DiffNormalized', 'Standardized']
      DO_CHUNK: True
      CHUNK_LENGTH: 180 # Original BigSmall: 3 (Maybe 1)
      CROP_FACE: # Experiment in the future 
        DO_CROP_FACE: False # Try true, False unique to BigSmall model only, but can try
        BACKEND: 'HC' # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False # Try true, False unique to BigSmall model only, but can try
        LARGE_BOX_COEF: 1.5
        DETECTION: # Experiment in the future | NOT FINAL
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False # This should be used ONLY if dynamic detection is used
      BIGSMALL:
        BIG_DATA_TYPE: ['Standardized']
        SMALL_DATA_TYPE: ['DiffNormalized']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9

VALID:
  DATA:
    FS: 30 # FPS of the video data
    DATASET: UBFCrPPG_BigSmall
    DO_PREPROCESS: True # If first time, should be True 
    DATA_FORMAT: NDCHW # NCDHW
    DATA_PATH: "data/UBFC-rPPG/RawData" # Raw dataset path, need to be updated
    CACHED_PATH: "data/UBFC-rPPG/PreprocessedData" # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "" 
    BEGIN: 0.7
    END: 0.85
    PREPROCESS:
      USE_PSUEDO_PPG_LABEL: True
      DATA_TYPE: ['DiffNormalized','Standardized'] # Can have multiple data type: ['Raw', 'DiffNormalized', 'Standardized']
      DATA_AUG: ['None'] # 'None' or 'Motion'. Use motion if the data is an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized # Can only choose ONE label type: ['Raw', 'DiffNormalized', 'Standardized']
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE: # Experiment in the future 
        DO_CROP_FACE: False # Try true, False unique to BigSmall model only, but can try
        BACKEND: 'HC' # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False # Try true, False unique to BigSmall model only, but can try
        LARGE_BOX_COEF: 1.5
        DETECTION: # Experiment in the future | NOT FINAL
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False # This should be used ONLY if dynamic detection is used
      BIGSMALL:
        BIG_DATA_TYPE: ['Standardized']
        SMALL_DATA_TYPE: ['DiffNormalized']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9

TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA', 'AU_METRICS']
  RUN_VALIDATION: True # To find the best epoch, should be True
  USE_BEST_EPOCH: True
  DATA:
    FS: 30 # FPS of the video data
    DATASET: UBFCrPPG_BigSmall
    DO_PREPROCESS: True # If first time, should be True 
    DATA_FORMAT: NDCHW # NCDHW
    DATA_PATH: "data/UBFC-rPPG/RawData" # Raw dataset path, need to be updated
    CACHED_PATH: "data/UBFC-rPPG/PreprocessedData" # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "" 
    BEGIN: 0.85
    END: 1.0
    PREPROCESS:
      USE_PSUEDO_PPG_LABEL: True
      LABEL_TYPE: DiffNormalized # Can only choose ONE label type: ['Raw', 'DiffNormalized', 'Standardized']
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE: # Experiment in the future 
        DO_CROP_FACE: False # Original BigSmall: False
        BACKEND: 'HC' # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False # Original BigSmall: False
        LARGE_BOX_COEF: 1.5
        DETECTION: # Experiment in the future | NOT FINAL
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30 # Original BigSmall: 180
          USE_MEDIAN_FACE_BOX: False # This should be used ONLY if dynamic detection is used
      BIGSMALL:
        BIG_DATA_TYPE: ['Standardized']
        SMALL_DATA_TYPE: ['DiffNormalized']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9


################################################
# ML MODELING SETTINGS
################################################
MODEL:
  NAME: BigSmall
  BIGSMALL:
    FRAME_DEPTH: 3

################################################
# COMPUTE RESOURCE SETTINGS
################################################
DEVICE: cuda:0 # cuda:0 or cpu
NUM_OF_GPU_TRAIN: 1 # 2 use single GPU to plot attention masks, mostly used on BigSmall model

################################################
# LOG SETTINGS
################################################
LOG:
  PATH: runs/exp

################################################
# INFERENCE SETTINGS
################################################
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT" # "FFT" or "Peak Detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10 # In seconds
  MODEL_PATH: ""