BASE: [''] # ALL ARE NOT FINAL
TOOLBOX_MODE: "train_and_test"  # "train_and_test", "only_test", "only_preprocess"

TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 9e-3
  MODEL_FILE_NAME: UBFCrPPG_DeepPhys
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30 # FPS of the video data
    DATASET: UBFC-rPPG
    DO_PREPROCESS: True # If first time, should be True 
    DATA_FORMAT: NDCHW # NCDHW
    DATA_PATH: "data/UBFC-rPPG/RawData" # Raw dataset path, need to be updated
    CACHED_PATH: "data/UBFC-rPPG/PreprocessedData" # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "" 
    BEGIN: 0.0 
    END: 0.667 
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized','Standardized'] # Can have multiple data type: ['Raw', 'DiffNormalized', 'Standardized']
      DATA_AUG: ['None'] # 'None' or 'Motion'. Use motion if the data is an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized # Can only choose ONE label type: ['Raw', 'DiffNormalized', 'Standardized']
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE: # Experiment in the future 
        DO_CROP_FACE: True # Try True
        BACKEND: 'HC' # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True # Try True
        LARGE_BOX_COEF: 1.5
        DETECTION: # Experiment in the future | NOT FINAL
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72 
        W: 72

VALID:
  DATA:
    FS: 30 # FPS of the video data
    DATASET: UBFC-rPPG
    DO_PREPROCESS: True # If first time, should be True 
    DATA_FORMAT: NDCHW # NCDHW
    DATA_PATH: "data/UBFC-rPPG/RawData" # Raw dataset path, need to be updated
    CACHED_PATH: "data/UBFC-rPPG/PreprocessedData" # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "" 
    BEGIN: 0.667
    END: 0.833
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized','Standardized']
      DATA_AUG: ['None'] # 'None' or 'Motion'. Use motion if the data is an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE: # Experiment in the future 
        DO_CROP_FACE: True # Try True
        BACKEND: 'HC' # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True # Try True
        LARGE_BOX_COEF: 1.5
        DETECTION: # Experiment in the future | NOT FINAL
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72

TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA', 'AU_METRICS']
  RUN_VALIDATION: True # To find the best epoch, should be True
  DATA:
    FS: 30 # FPS of the video data
    DATASET: UBFC-rPPG
    DO_PREPROCESS: True # If first time, should be True 
    DATA_FORMAT: NDCHW # NCDHW
    DATA_PATH: "data/UBFC-rPPG/RawData" # Raw dataset path, need to be updated
    CACHED_PATH: "data/UBFC-rPPG/PreprocessedData" # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "" 
    BEGIN: 0.833
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized','Standardized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE: # Experiment in the future 
        DO_CROP_FACE: True # Try True
        BACKEND: 'HC' # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True # Try True
        LARGE_BOX_COEF: 1.5
        DETECTION: # Experiment in the future | NOT FINAL
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72


################################################
# ML MODELING SETTINGS
################################################
MODEL:
  NAME: DeepPhys
  DROP_RATE: 0.2

################################################
# COMPUTE RESOURCE SETTINGS
################################################
DEVICE: cpu # cuda:0 or cpu
NUM_OF_GPU_TRAIN: 1 # 2 use single GPU to plot attention masks

################################################
# LOG SETTINGS
################################################
LOG:
  PATH: runs/exp

################################################
# INFERENCE SETTINGS
################################################
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT" # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10 # In seconds
  MODEL_PATH: ""